In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
import random
x = random.random()
print(x)

0.6719644450974988


In [5]:
! pwd


/content


In [6]:
! ls


sample_data


In [7]:
x =torch.Tensor([5,3])
y =torch.Tensor([2,1])
print(x*y)

tensor([10.,  3.])


In [8]:
x = torch.zeros([2,5])

In [9]:
print

<function print>

In [10]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [11]:
x.shape

torch.Size([2, 5])

In [12]:
y = torch.rand([2,5])

In [13]:
print(y)

tensor([[0.5738, 0.1100, 0.5175, 0.4232, 0.2731],
        [0.4213, 0.7288, 0.5181, 0.7968, 0.1828]])


In [15]:
y = y.view([2,5])

In [16]:
y

tensor([[0.5738, 0.1100, 0.5175, 0.4232, 0.2731],
        [0.4213, 0.7288, 0.5181, 0.7968, 0.1828]])